name: Build and Release subcollector

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build subcollector binary
        shell: bash
        run: |
          mkdir -p dist

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            BINARY_NAME="subcollector-windows-amd64.exe"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            BINARY_NAME="subcollector-darwin-amd64"
          else
            BINARY_NAME="subcollector-linux-amd64"
          fi

          go build -o dist/$BINARY_NAME ./cmd/subcollector

      - name: List files for debugging
        run: ls -la dist

      - name: Upload subcollector binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/$BINARY_NAME
          asset_name: $BINARY_NAME
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}